[package]
name = "housou"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
send = ["passkey-server/send"]
dev = []                       # Use local data.json instead of fetching from GitHub


[dependencies]
passkey-server = { path = "crates/passkey", default-features = false, features = [
    "wasm",
] }
d1-orm = { path = "crates/d1-orm", features = ["d1"] }
worker = { version = "0.7.4", features = ["d1"] }
url = "2.5"
serde = { workspace = true }
serde_derive = "1.0.228"
serde_json = { workspace = true }
console_error_panic_hook = "0.1.7"
regex = "1.12.3"
js-sys = { workspace = true }
futures = "0.3.32"
argon2 = "0.5"
rand_core = "0.10"
uuid = { version = "1.8", features = ["v4", "fast-rng", "js", "serde"] }
cookie = "0.18"
getrandom = { version = "0.4", features = ["wasm_js"] }
async-trait = { workspace = true }
tmdb_client = { git = "https://github.com/asutorufa/tmdb-client-rs.git", rev = "17adf938c1d9831dc150a73d59bf2ec6b186d23c", default-features = false, features = [
    "async",
] }
rust-anilist = { git = "https://github.com/Asutorufa/rust-anilist", rev = "f3074c0", default-features = false }
sha2 = "0.10.9"
hmac = "0.12.1"
hex = "0.4.3"
serde_repr = "0.1.20"
serde_urlencoded = "0.7.1"
time = { version = "0.3", features = ["macros", "wasm-bindgen", "parsing"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[workspace]
members = ["crates/passkey", "crates/d1-orm"]

[workspace.dependencies]
js-sys = "0.3.88"
rusqlite = { version = "0.38", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
d1-orm = { path = "crates/d1-orm", features = ["sqlite"] }
rusqlite = { workspace = true }
tokio = { workspace = true }
