name = "housou"
main = "build/worker/shim.mjs"
compatibility_date = "2024-02-07"

[build]
command = """
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
. $HOME/.cargo/env && \
rustup target add wasm32-unknown-unknown && \
npm install --prefix web && \
npm run build --prefix web && \
cargo install -q worker-build && \
worker-build --release"""

[assets]
directory = "./web/dist"

[vars]
# Defined in .dev.vars for local development
# TMDB_TOKEN = ""

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "housou-db"
database_id = "c04e350d-f778-42e6-b0a6-156c5eb56a46"

[env.dev]

[env.dev.build]
command = "cargo install -q worker-build && worker-build --release --features dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "housou-db"
database_id = "c04e350d-f778-42e6-b0a6-156c5eb56a46"

[env.production]
[env.production.vars]
# Use `wrangler secret put TMDB_TOKEN` for production
# TMDB_TOKEN = ""
[env.production.build]
command = """
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
. $HOME/.cargo/env && \
rustup target add wasm32-unknown-unknown && \
npm install --prefix web && \
npm run build --prefix web && \
cargo install -q worker-build && \
worker-build --release"""

[[env.production.d1_databases]]
binding = "DB"
database_name = "housou-db"
database_id = "c04e350d-f778-42e6-b0a6-156c5eb56a46"
