[package]
name = "d1-orm"
version = "0.1.2"
edition = "2021"
description = "A lightweight ORM/SQL builder for Cloudflare D1 and SQLite"
repository = "https://github.com/Asutorufa/housou/tree/master/crates/d1-orm"
license = "MIT"
keywords = ["orm", "cloudflare-d1", "sqlite", "sql-builder", "wasm"]
categories = ["database", "wasm", "web-programming"]

[dependencies]
serde = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }

# D1 backend
worker = { workspace = true, features = ["d1"], optional = true }
js-sys = { workspace = true, optional = true }

# Sqlite backend
rusqlite = { workspace = true, optional = true }
hex = { version = "0.4.3", optional = true }

[features]
default = []
d1 = ["dep:worker", "dep:js-sys"]
sqlite = ["dep:rusqlite", "dep:hex"]

[dev-dependencies]
tokio = { workspace = true }
