[package]
name = "passkey"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
base64 = "0.22"
coset = "0.4"
ciborium = "0.2"
p256 = { version = "0.13", features = ["ecdsa", "std"] }
sha2 = "0.10"
uuid = { version = "1.8", features = ["v4", "serde"] }
thiserror = "1.0"
getrandom = { version = "0.4", features = [
    "wasm_js",
] } # keeping consistent with root for WASM target
rand_core = "0.10"


[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
