[package]
name = "passkey-server"
version = "0.1.4"
edition = "2021"
description = "A generic, storage-agnostic Passkey (WebAuthn) server implementation."
repository = "https://github.com/Asutorufa/housou/tree/master/crates/passkey"
license = "MIT"
keywords = ["passkey", "webauthn", "fido2", "authentication", "wasm"]
categories = ["authentication", "web-programming", "wasm"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
base64 = "0.22"
coset = "0.4.2"
ciborium = "0.2"
p256 = { version = "0.13", features = ["ecdsa", "std"] }
sha2 = "0.11"
uuid = { version = "1.23.1", features = ["v4", "serde"] }
getrandom = "0.4.2"
rand_core = "0.10.1"

[features]
default = []
send = []
wasm = ["getrandom/wasm_js"]


[dev-dependencies]
tokio = { workspace = true }
axum = "0.8.9"
tower-http = { version = "0.6", features = ["cors"] }
serde_json = { workspace = true }

[[example]]
name = "basic"
required-features = ["send"]
